### ISSUE TITLE
Blog article has accuracy issue with security statements

### ISSUE THREAD

**Issue by RossWilliams** [aws-samples/aws-appsync-survey-tool#1]
<blockquote>However, it only allows standard users to read the Survey object if their group membership matches with a group name defined in a Survey’s attributes.</blockquote>

Subscriptions are not disabled, so auth does not fulfill the above security controls. This is not a secure solution and a customer using this as a guide may be putting their customers in danger. 

Could you  turn off subscriptions in this project and in the AWS mobile blog post?

**Comment by robcost** [comment]
Thank you taking the time to review the code and raising this @RossWilliams. Per your request I have updated the GraphQL schema to disable subscriptions.

**Comment by KoldBrewEd** [comment]
Subscriptions don't need to be disabled: https://aws-amplify.github.io/docs/cli-toolchain/graphql#authorizing-subscriptions

**Comment by RossWilliams** [comment]
@awsed This project utilises dynamic group authorisation.  Per your link, "Dynamic groups have no impact to subscriptions. You will not get notified of any updates to them." Suggests you still need to turn them off for your use case unless I'm reading the documentation wrong.
Also, seems like a choice needed to be made between turning subscriptions off vs. adding the IoT endpoint to the readme diagram.

**Comment by KoldBrewEd** [comment]
@RossWilliams According to the blog post the groups are created on Cognito which means they are static groups.

**Comment by RossWilliams** [comment]
@awsed Ok, maybe I'm wrong about the definition of dynamic groups, but the repo schema has:
```
{allow: groups, groupsField: "groups", operations: [read]}
```
I think reading the allowed group from an item property is what is meant by dynamic group.
