### ISSUE TITLE
how to identify no of active subscribers by subscription in appsync

### ISSUE THREAD

**Issue by ghost** [aws-samples/aws-appsync-survey-tool#2]
Need to keep count of how many subscribers are connected with each subscription.

For UserA, UserB are connected with SubscriptionA : then 2 is the total subscribers
For UserA are connected with SubscriptionB : then 1 is the total subscribers

Can i know when UserA unsubscribes , subscribes, disconnects, reconnects from AppSync ?

**Comment by robcost** [comment]
Hi @kushptlapigarage, it looks like you've opened the same issue in multiple repos, I'll close this one as this project does not use Subscriptions.
